### ISSUE TITLE
Not working on Windows 10

### ISSUE THREAD

**Issue by PhilAndrew** [bytedeco/sbt-javacv#5]
```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: putMemberOffset
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1929)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1814)
    at java.lang.Runtime.load0(Runtime.java:809)
    at java.lang.System.load(System.java:1083)
    at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:637)
    at org.bytedeco.javacpp.Loader.load(Loader.java:492)
    at org.bytedeco.javacpp.Loader.load(Loader.java:409)
    at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at org.bytedeco.javacpp.Loader.load(Loader.java:464)
    at org.bytedeco.javacpp.Loader.load(Loader.java:409)
    at org.bytedeco.javacpp.opencv_imgcodecs.<clinit>(opencv_imgcodecs.java:13)
    at opencv2_cookbook.chapter01.Ex2MyFirstGUIApp$.opencv2_cookbook$chapter01$Ex2MyFirstGUIApp$$openImage(Ex2MyFirstGUIApp.scala:130)
    at opencv2_cookbook.chapter01.Ex2MyFirstGUIApp$$anon$2$$anonfun$1.apply$mcV$sp(Ex2MyFirstGUIApp.scala:55)
    at scala.swing.Action$$anon$2.apply(Action.scala:65)
    at scala.swing.Action$$anon$1.actionPerformed(Action.scala:83)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.Component.processMouseEvent(Component.java:6525)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:719)
    at java.awt.EventQueue$4.run(EventQueue.java:717)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

More details.

Its creating a directory at `C:\Users\philip\AppData\Local\Temp\javacpp105687008440412`

It downloads these files

```
msvcp120.dll
msvcr120.dll
opencv_core300.dll
opencv_imgproc300.dll
jniopencv_core.dll
```

I think it fails on jniopencv_core.dll

The exception is thrown on this line

 tempFile.deleteOnExit();

In file Loader.java

**Comment by lloydmeta** [comment]
It's strange that the failure (according to the stack trace) is on `putMemberOffset` not being found 😕 .  I've seen this kind of error before (`NoSuchMethodError`), and it is usually because there are multiple versions of the same library in your classpath, but it could be a red herring for more serious errors. Just in case, can you try a `clean` (or `sbt clean` if from normal command prompt) and see if it helps?

Also, what version of SBT-JavaCV are you using? It might help to have a dependency graph of what libs you are using in your current project (see [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph)).

I certainly hope it isn't failing on `tempFile.deleteOnExit();`, since that is a standard Java method O_o. Is there any reason why you think that is where the exception is being thrown?

**Comment by PhilAndrew** [comment]
Thanks, your probably right, my project is big with many dependencies, let me check.
